### ISSUE TITLE
Can you check in your test data?

### ISSUE THREAD

**Issue by ranford** [ecobost/scanreader-matlab#1]
Hi,

I was playing around on GitHub and I noticed your repo and its tests. I actually know very little (read:nothing) about your domain and what the repo actually does, but it looks like you have some nice tests going on. 

Anyway, I forked your repo and tried to run your tests because I am experimenting with finding code coverage on "real" code, but your tests dont work without the data folder. Can you add that to the repo?

**Comment by ecobost** [comment]
Hi, 
It's a bit hard to add the data folder because it has many little scans and it ends up being around 5-6 GB. If you find an easy way, I may be able to send it to you. Also, https://github.com/atlab/scanreader (the python version of this repo) has the same tests written in Python if that's of any interest to you (still no data, though).
Cheers,

**Comment by ranford** [comment]
ah I see. thats interesting. what about pcloud?

https://transfer.pcloud.com/

Perhaps the data can be compressed to be under 5 GB?

Thanks for entertaining the idea. I am most interested in the MATLAB code as I am looking to see different ways to show and integrate matlab code coverage.

**Comment by ecobost** [comment]
Sent it
